export { default as DashboardView } from './DashboardView'
export { default as CategoriesView } from './categories/CategoriesView' 
export { default as ProductsView } from './products/ProductsView'
export { default as WarehouseView } from './warehouses/WarehousesView'
export { default as InventoryView } from './inventory/InventoryView'
export { default as MovementsView } from './movements/MovementsView'
export { default as DeletedView } from './deleted/DeletedView'
export { default as CategoriesDeleteView } from './categories/CategoriesDeletedView'
